name: Workflow Demo

on: push



jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: setup pyenv
      run: python -m venv pyenv
    - name: install ansible
      run: |
        source pyenv/bin/activate
        pip install ansible==11.7.0
    - name: test ansible
      run: ansible-playbook -h