name: Workflow Demo

on:
  push:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment'
        required: true
        type: choice
        options:
          - staging
          - production
          - testing
      version:
        description: 'Application version to deploy'
        required: true
        default: '1.0.0'

jobs: 
  test_ansible:
    if: github.ref == 'refs/heads/main'
    runs-on: self-hosted
    permissions: 
      packages: write
    env:
      KUBECONFIG:  kubeconfig

    steps:
    - name: checkout_repo
      uses: actions/checkout@v4
    - name: cache deps
      uses: actions/cache@v4
      with:
        key: python-cache-${{ hashFiles('.github/workflows/requirements.txt') }}
        path: pyenv
    - name: setup pyenv
      run: python -m venv pyenv
    - name: install ansible
      run: |
        source pyenv/bin/activate
        pip install -r .github/workflows/requirements.txt
    - name: test ansible
      run: ansible-playbook --version
    - name: test ansible
      run: ansible-doc copy
    - name: write kubeconfig
      run: echo "${{ secrets.KUBECONFIG }}" > kubeconfig
    - name: test kubectl
      run:  kubectl get nodes
  




