name: Workflow Demo

on: push

jobs:  
  test_ansible:
    runs-on: ubuntu-latest
    steps:
    - name: cache deps
      uses: actions/cache@v4
      with:
        key: ansible-cache
        path: pyenv
    - name: setup pyenv
      run: python -m venv pyenv
    - name: install ansible
      run: |
        source pyenv/bin/activate
        pip install ansible==11.7.0
    - name: test ansible
      run: ansible-playbook --version