name: Workflow Demo

on: 

#env:
#  ACCESS_ID: ${{ vars.ACCESS_ID }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: install ansible
      run: apt-get install ansible
    - name: show modules
      run: ansible-doc -l
    - name: Echo ACCESS_ID
      run: echo ${{ vars.ACCESS_ID }}