name: Workflow Demo

on: push

jobs: 
  test_ansible:
    runs-on: self-hosted
    permissions: 
      packages: write

    steps:
    - name: checkout_repo
      uses: actions/checkout@v4
    - name: cache deps
      uses: actions/cache@v4
      with:
        key: python-cache-${{ hashFiles('.github/workflows/requirements.txt') }}
        path: pyenv
    - name: setup pyenv
      run: python -m venv pyenv
    - name: install ansible
      run: |
        source pyenv/bin/activate
        pip install -r .github/workflows/requirements.txt
    - name: test ansible
      run: ansible-playbook --version
    - name: test ansible
      run: ansible-doc copy
    - name: run kubectl
      run: |
        echo ${{ secrets.KUBECONFIG }} > kubeconfig
        kubectl --kubeconfig kubeconfig get nodes





