name: Workflow Demo

on: push

#env:
#  ACCESS_ID: ${{ vars.ACCESS_ID }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: setup pyenv
      run: python -m venv pyenv
    - name: install ansible
      run: |
        source pyenv/bin/activate
        pip install ansible
    - name: test ansible
      run: ansible-doc -l